version: "3"

services:
  auth-service-http:
    build: ./auth_service
    container_name: auth_service_http
    env_file: auth_service/.env
    restart: always
    depends_on:
      - auth-service-db

  user-service-db:
    image: postgres:latest
    env_file: ./user_service/.env
    ports:
      - "5432:5432"
    volumes: 
      - user_async_service_postgres_data:/var/lib/postgresql/data
    restart: always

  notes-service-db:
    image: postgres:latest
    env_file: ./notes_service/.env
    ports:
      - "5433:5432"
    volumes:
      - notes_async_service_postgres_data:/var/lib/postgresql/data
    restart: always

  auth-service-db:
    image: postgres:latest
    env_file: ./auth_service/.env
    ports:
      - "5434:5432"
    volumes:
      - auth_async_service_postgres_data:/var/lib/postgresql/data
    restart: always

  awesome-notes-nginx:
    build: ./nginx/
    container_name: awesome-notes-nginx
    depends_on:
      - auth-service-http
    restart: on-failure
    ports: 
      - "80:80"

volumes:
  user_async_service_postgres_data:
  notes_async_service_postgres_data:
  auth_async_service_postgres_data: